#!/bin/sh

# Set JAVA_HOME to the location of your JDK
#JAVA_HOME=/usr/java/jdk1.5.0

# Set BASE to where you have installed jfacl
BASE=/home/staff/nrs/java/jfacl

LD_LIBRARY_PATH=${BASE}/lib/`/bin/uname`:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH

exec ${JAVA_HOME}/bin/java -classpath ${BASE}/jfacl.jar -Dbase=${BASE} uk.ac.bham.cs.security.acl.UfsAclWin $* 
