#!/bin/sh

JAVA=`which java`
if [ -z "$JAVA" ]; then
	echo "Cannot find java in your path"
	exit 1
fi

[ -h $0 ] && BIN=`readlink $0` || BIN=$0
LIB=`dirname $BIN | sed 's_/[^/]\+$__'`/lib

# Set THEME to the Java theme you prefer
# 'ocean' is the new Java 5.0 style, I prefer the classic 'steel' look
#THEME=ocean
THEME=steel

KERNEL=`/bin/uname -s`
if [ "${KERNEL}" = "Linux" ]; then
	ARCH=`/bin/uname -m`
elif [ "${KERNEL}" = "SunOS" ]; then
	ARCH=`/bin/uname -p`
fi

exec ${JAVA} -Djava.library.path=${LIB} -Dswing.metalTheme=${THEME} -jar ${LIB}/jfacl.jar "$*" 
