CC=gcc
CFLAGS=-I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux -fPIC -DLINUX
LDFLAGS=-shared -lacl
ARCH=`/bin/uname -s`/`/bin/uname -m`

OBJS=jacl.o getname.o getall.o linux/uacl.o

all: libjacl.so
	ant

libjacl.so: $(OBJS)
	$(CC) -o $@ $(OBJS) $(LDFLAGS)

.c.o :
	$(CC) $(CFLAGS) $(INCLUDE) -c -g $*.c -o $*.o

install: libjacl.so
	install -d ../lib/$(ARCH)
	install libjacl.so ../lib/$(ARCH)
	ant install

clean::
	$(RM) libjacl.so *.o linux/*.o
	ant clean
