PREFIX=/usr/local
CC=gcc
CFLAGS=-I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/solaris -Wall
LDFLAGS=-G -lsec
OBJS=jacl.o getname.o getall.o
HEADERS=org_flimbar_security_auth_module_Posix.h ufsaclwin.h getname.h

include Makefile.common
