PREFIX=/usr/local
CC=gcc
CFLAGS=-I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux -fPIC -DLINUX
LDFLAGS=-shared -lacl
OBJS=jacl.o getname.o getall.o linux/uacl.o
HEADERS=org_flimbar_security_auth_module_Posix.h ufsaclwin.h linux/uacl.h getname.h

include Makefile.common
