/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_flimbar_security_auth_module_Posix */

#ifndef _Included_org_flimbar_security_auth_module_Posix
#define _Included_org_flimbar_security_auth_module_Posix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_flimbar_security_auth_module_Posix
 * Method:    getUserByName
 * Signature: (Ljava/lang/String;)Lorg/flimbar/security/auth/UnixUser;
 */
JNIEXPORT jobject JNICALL Java_org_flimbar_security_auth_module_Posix_getUserByName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_flimbar_security_auth_module_Posix
 * Method:    getUserByUid
 * Signature: (J)Lorg/flimbar/security/auth/UnixUser;
 */
JNIEXPORT jobject JNICALL Java_org_flimbar_security_auth_module_Posix_getUserByUid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_flimbar_security_auth_module_Posix
 * Method:    getGroupByName
 * Signature: (Ljava/lang/String;)Lorg/flimbar/security/auth/UnixGroup;
 */
JNIEXPORT jobject JNICALL Java_org_flimbar_security_auth_module_Posix_getGroupByName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_flimbar_security_auth_module_Posix
 * Method:    getGroupByGid
 * Signature: (J)Lorg/flimbar/security/auth/UnixGroup;
 */
JNIEXPORT jobject JNICALL Java_org_flimbar_security_auth_module_Posix_getGroupByGid
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
