/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_ac_bham_cs_security_auth_module_Posix */

#ifndef _Included_uk_ac_bham_cs_security_auth_module_Posix
#define _Included_uk_ac_bham_cs_security_auth_module_Posix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_ac_bham_cs_security_auth_module_Posix
 * Method:    getUserByName
 * Signature: (Ljava/lang/String;)Luk/ac/bham/cs/security/auth/module/Posix;
 */
JNIEXPORT jobject JNICALL Java_uk_ac_bham_cs_security_auth_module_Posix_getUserByName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     uk_ac_bham_cs_security_auth_module_Posix
 * Method:    getUserByUid
 * Signature: (J)Luk/ac/bham/cs/security/auth/module/Posix;
 */
JNIEXPORT jobject JNICALL Java_uk_ac_bham_cs_security_auth_module_Posix_getUserByUid
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
