/*
 * Copyright (C) 2003-2006 Nick Shrine <N.R.Shrine@cs.bham.ac.uk>
 *
 * This file is part of Jfacl.
 *
 * Jfacl is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * Jfacl is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Jfacl; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * NameDialog.java
 *
 * Created on 16 January 2006, 11:41
 */

package uk.ac.bham.cs.security.acl;

import java.util.*;
import javax.swing.*;

import static uk.ac.bham.cs.security.acl.UfsAclEntry.*;

/**
 *
 * @author  nrs
 */
public class NameDialog extends javax.swing.JDialog {
    
    public static final String SPLIT_CHAR = ";";
    
    private final AddDialog adialog;
    
    /** Creates new form NameDialog */
    public NameDialog(AddDialog adialog, boolean modal) {
        super(adialog.getParent(), modal);
        this.adialog = adialog;
        initComponents();
        setLocationRelativeTo(adialog);
    }
    
    private void addEntries(boolean defaults) {
        String text = namesArea.getText().trim();
        String[] names = text.split(SPLIT_CHAR);        
        UfsAclEntry[] toAdd = new UfsAclEntry[names.length];
        Set<String> notFound = new HashSet<String>();
        
        int type = 0;
        if (userRadioButton.isSelected()) {
            type = USER;
        } else if (groupRadioButton.isSelected()) {
            type = GROUP;
        }
        
        for (int i = 0; i < names.length; i++) {
            String name = names[i].trim();
            toAdd[i] = adialog.getEntryByName(name, type);            
            if (toAdd[i] == null) {
                notFound.add(name);
            }                           
        }
        
        if (notFound.isEmpty()) {
            adialog.addEntries(toAdd, defaults);    
            dispose();
        } else {
            StringBuilder sb = new StringBuilder();
            for (String name : notFound) {
                sb.append(name + " ");
            }
            JOptionPane.showMessageDialog(this, "Name(s) not found: "
                    + sb.toString(),
                    (type == USER ? "User" : "Group") + " unknown",
                    JOptionPane.WARNING_MESSAGE);
            
        }        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        namesArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        userRadioButton = new javax.swing.JRadioButton();
        groupRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        defButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        namesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Users or Groups");
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jPanel1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        namesArea.setColumns(20);
        namesArea.setRows(4);
        namesArea.setToolTipText("Enter names separated by a semicolon");
        namesArea.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(namesArea);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Type"));
        buttonGroup1.add(userRadioButton);
        userRadioButton.setSelected(true);
        userRadioButton.setText("User");
        jPanel3.add(userRadioButton);

        buttonGroup1.add(groupRadioButton);
        groupRadioButton.setText("Group");
        jPanel3.add(groupRadioButton);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        addButton.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        addButton.setLabel("Add");
        addButton.setPreferredSize(new java.awt.Dimension(70, 25));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jPanel2.add(addButton);

        defButton.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        defButton.setEnabled(adialog.DEFAULTS);
        defButton.setLabel("Add Default");
        defButton.setPreferredSize(new java.awt.Dimension(100, 25));
        defButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defButtonActionPerformed(evt);
            }
        });

        jPanel2.add(defButton);

        cancelButton.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelButton.setLabel("Cancel");
        cancelButton.setPreferredSize(new java.awt.Dimension(70, 25));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jPanel2.add(cancelButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        namesLabel.setText("Enter the names to select");
        namesLabel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        getContentPane().add(namesLabel, java.awt.BorderLayout.NORTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void defButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defButtonActionPerformed
        addEntries(true);
    }//GEN-LAST:event_defButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addEntries(false);
    }//GEN-LAST:event_addButtonActionPerformed
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton defButton;
    private javax.swing.JRadioButton groupRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextArea namesArea;
    private javax.swing.JLabel namesLabel;
    private javax.swing.JRadioButton userRadioButton;
    // End of variables declaration//GEN-END:variables
    
}
